// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api_listener.djinni

#import "WALHttpError.h"
#import <Foundation/Foundation.h>


@protocol WALApiListener

- (void)onNetworkError:(nonnull WALHttpError *)error;

- (void)onSuccess:(int16_t)httpCode
             data:(nonnull NSString *)data;

@end
