// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from billing_address_vm.djinni

#import <Foundation/Foundation.h>

@interface WALBillingAddressVm : NSObject
- (nonnull instancetype)initWithBillingAddressId:(int64_t)billingAddressId
                                         address:(nonnull NSString *)address
                                        address2:(nonnull NSString *)address2
                                            city:(nonnull NSString *)city
                                   stateProvince:(nonnull NSString *)stateProvince
                                         zipCode:(nonnull NSString *)zipCode
                                         country:(nonnull NSString *)country
                                         vatCode:(nonnull NSString *)vatCode
                                      fiscalCode:(nonnull NSString *)fiscalCode
                                            name:(nonnull NSString *)name
                                       isDefault:(BOOL)isDefault;
+ (nonnull instancetype)billingAddressVmWithBillingAddressId:(int64_t)billingAddressId
                                                     address:(nonnull NSString *)address
                                                    address2:(nonnull NSString *)address2
                                                        city:(nonnull NSString *)city
                                               stateProvince:(nonnull NSString *)stateProvince
                                                     zipCode:(nonnull NSString *)zipCode
                                                     country:(nonnull NSString *)country
                                                     vatCode:(nonnull NSString *)vatCode
                                                  fiscalCode:(nonnull NSString *)fiscalCode
                                                        name:(nonnull NSString *)name
                                                   isDefault:(BOOL)isDefault;

@property (nonatomic, readonly) int64_t billingAddressId;

@property (nonatomic, readonly, nonnull) NSString * address;

@property (nonatomic, readonly, nonnull) NSString * address2;

@property (nonatomic, readonly, nonnull) NSString * city;

@property (nonatomic, readonly, nonnull) NSString * stateProvince;

@property (nonatomic, readonly, nonnull) NSString * zipCode;

@property (nonatomic, readonly, nonnull) NSString * country;

@property (nonatomic, readonly, nonnull) NSString * vatCode;

@property (nonatomic, readonly, nonnull) NSString * fiscalCode;

@property (nonatomic, readonly, nonnull) NSString * name;

@property (nonatomic, readonly) BOOL isDefault;

@end
