// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from billing_address_list.djinni

#import <Foundation/Foundation.h>
@class WALBillingAddressDetailAddPresenter;


@protocol WALBillingAddressDetailAddView

- (void)setAddPresenter:(nullable WALBillingAddressDetailAddPresenter *)presenter;

@end
