// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from billing_address_list.djinni

#import "WALBillingAddressVm.h"
#import <Foundation/Foundation.h>
@class WALBillingAddressDetailUpdatePresenter;


@protocol WALBillingAddressDetailUpdateView

- (void)showBusinessAddress:(nonnull WALBillingAddressVm *)billingAddress;

- (void)setUpdatePresenter:(nullable WALBillingAddressDetailUpdatePresenter *)presenter;

@end
