// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from billing_address_list.djinni

#import "WALBillingAddressVm.h"
#import <Foundation/Foundation.h>


@interface WALBillingAddressDetailAddPresenter : NSObject

- (void)addBusinessAddress:(nonnull WALBillingAddressVm *)billingAddress;

@end
