// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from billing_address_list.djinni

#import "WALBillingAddressVm.h"
#import <Foundation/Foundation.h>
@class WALBillingAddressListPresenter;


@protocol WALBillingAddressListView

- (void)showNoContentMessage;

- (void)showBillingAddresses:(nonnull NSArray<WALBillingAddressVm *> *)billingAddresses;

- (void)reloadEntries;

- (void)setPresenter:(nullable WALBillingAddressListPresenter *)presenter;

@end
