// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from core_views_builder.djinni

#import "WALUiRouteInformation.h"
#import <Foundation/Foundation.h>
@protocol WALBillingAddressDetailAddView;
@protocol WALBillingAddressDetailUpdateView;
@protocol WALBillingAddressListView;


@protocol WALCoreViewsBuilder

- (nullable id<WALBillingAddressListView>)openBillingAddressListView:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALBillingAddressDetailAddView>)openBillingAddressDetailAddView:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALBillingAddressDetailUpdateView>)openBillingAddressDetailUpdateView:(nonnull WALUiRouteInformation *)uiRouteInformation;

@end
