// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from credit_card_vm.djinni

#import <Foundation/Foundation.h>

@interface WALCreditCardVm : NSObject
- (nonnull instancetype)initWithFavourite:(BOOL)favourite
                                    alias:(nonnull NSString *)alias
                                   holder:(nonnull NSString *)holder
                                      pan:(nonnull NSString *)pan
                                brandLogo:(nonnull NSString *)brandLogo
                              expireMonth:(int64_t)expireMonth
                               expireYear:(int64_t)expireYear
                             securityCode:(nonnull NSString *)securityCode
                                lastUsage:(nonnull NSString *)lastUsage;
+ (nonnull instancetype)creditCardVmWithFavourite:(BOOL)favourite
                                            alias:(nonnull NSString *)alias
                                           holder:(nonnull NSString *)holder
                                              pan:(nonnull NSString *)pan
                                        brandLogo:(nonnull NSString *)brandLogo
                                      expireMonth:(int64_t)expireMonth
                                       expireYear:(int64_t)expireYear
                                     securityCode:(nonnull NSString *)securityCode
                                        lastUsage:(nonnull NSString *)lastUsage;

@property (nonatomic, readonly) BOOL favourite;

@property (nonatomic, readonly, nonnull) NSString * alias;

@property (nonatomic, readonly, nonnull) NSString * holder;

@property (nonatomic, readonly, nonnull) NSString * pan;

@property (nonatomic, readonly, nonnull) NSString * brandLogo;

@property (nonatomic, readonly) int64_t expireMonth;

@property (nonatomic, readonly) int64_t expireYear;

@property (nonatomic, readonly, nonnull) NSString * securityCode;

@property (nonatomic, readonly, nonnull) NSString * lastUsage;

@end
