// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from core_routes.djinni

#import <Foundation/Foundation.h>

@interface WALCoreRoutes : NSObject
- (nonnull instancetype)init;
+ (nonnull instancetype)coreRoutes;

@end

extern NSString * __nonnull const WALCoreRoutesRouteCoreBase;
extern NSString * __nonnull const WALCoreRoutesRouteBillingAddressesList;
extern NSString * __nonnull const WALCoreRoutesRouteBillingAddressDetail;
extern NSString * __nonnull const WALCoreRoutesRouteBillingAddressAdd;
