// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from core.djinni

#import "WALRouterType.h"
#import <Foundation/Foundation.h>
@class WALCore;
@class WALUiRouter;
@protocol WALCoreParamsInterface;
@protocol WALUiNativeRouter;


@interface WALCore : NSObject

+ (nullable WALCore *)createCore:(nullable id<WALCoreParamsInterface>)coreParamsInterface;

/** important: call this method after the ppa_core object creation! */
- (void)setupCore;

- (nullable WALUiRouter *)getUiRouter;

- (void)configurePerypheralRouter:(WALRouterType)routerType
                     nativeRouter:(nullable id<WALUiNativeRouter>)nativeRouter;

- (nullable WALUiRouter *)getPerypheralRouter:(WALRouterType)routerType;

- (void)setNativeRouter:(nullable id<WALUiNativeRouter>)uiNativeRouter;

@end
