// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from device_informations.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, WALDeviceOs)
{
    WALDeviceOsDeviceOsUnknown,
    WALDeviceOsDeviceOsAndroid,
    WALDeviceOsDeviceOsIOS,
    WALDeviceOsDeviceOsWebBrowser,
    WALDeviceOsDeviceOsMacOS,
    WALDeviceOsDeviceOsWindows,
    WALDeviceOsDeviceOsUnix,
    WALDeviceOsDeviceOsOther,
};
