// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from device_informations.djinni

#import "WALDeviceOs.h"
#import <Foundation/Foundation.h>


@protocol WALDeviceInformations

- (BOOL)getIsNFCAvailable;

- (nonnull NSString *)getDeviceName;

- (nonnull NSString *)getImei;

- (nonnull NSString *)getOSName;

- (nonnull NSString *)getOSVersion;

- (nonnull NSString *)getSerialNumber;

- (WALDeviceOs)getOSType;

@end
