// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from date_formatter.djinni

#import <Foundation/Foundation.h>


@protocol WALDateFormatter

- (nonnull NSString *)format:(int64_t)timeToFormat;

@end
