// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from event_loop.djinni

#import <Foundation/Foundation.h>
@class WALAsyncTask;


@protocol WALEventLoop

- (void)post:(nullable WALAsyncTask *)task;

@end
