// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api_call.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, WALHttpAction)
{
    WALHttpActionGet,
    WALHttpActionPost,
    WALHttpActionPut,
    WALHttpActionDelete,
};
