// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network-interfaces.djinni

#import <Foundation/Foundation.h>

@interface WALHttpError : NSObject
- (nonnull instancetype)initWithErrorCode:(int16_t)errorCode
                              errorDomain:(nonnull NSString *)errorDomain
                         errorDescription:(nonnull NSString *)errorDescription;
+ (nonnull instancetype)httpErrorWithErrorCode:(int16_t)errorCode
                                   errorDomain:(nonnull NSString *)errorDomain
                              errorDescription:(nonnull NSString *)errorDescription;

@property (nonatomic, readonly) int16_t errorCode;

@property (nonatomic, readonly, nonnull) NSString * errorDomain;

@property (nonatomic, readonly, nonnull) NSString * errorDescription;

@end
