// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from i18n.djinni

#import <Foundation/Foundation.h>


@protocol WALI18n

- (nonnull NSString *)localizedString:(nonnull NSString *)key;

@end
