// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from lifecycle.djinni

#import <Foundation/Foundation.h>


@interface WALLifecycle : NSObject

- (void)start;

- (void)resume;

- (void)pause;

- (void)stop;

@end
