// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_registration_step_1.djinni

#import "WALPpaWalletType.h"
#import <Foundation/Foundation.h>
@class WALPpaRegistrationStep1Presenter;


@protocol WALPpaRegistrationStep1View

- (void)setPresenter:(nullable WALPpaRegistrationStep1Presenter *)presenter;

- (void)setPaymentType:(WALPpaWalletType)walletType;

@end
