// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_top_bar.djinni

#import <Foundation/Foundation.h>


@interface WALPpaTopBarPresenter : NSObject

- (void)back;

- (void)selectUserMenu;

- (void)close;

@end
