// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_insert_secret_code.djinni

#import <Foundation/Foundation.h>


@interface WALPpaInsertSecretCodePresenter : NSObject

- (void)proceed:(nonnull NSString *)secretCode;

@end
