// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_registration_method_default.djinni

#import <Foundation/Foundation.h>


@interface WALPpaRegistrationMethodDefaultPresenter : NSObject

- (void)close;

@end
