// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_web_payment.djinni

#import <Foundation/Foundation.h>


@interface WALPpaWebPaymentPresenter : NSObject

- (void)cancel;

- (void)proceed:(nonnull NSString *)completeCloseUrl;

@end
