// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_web_operation.djinni

#import "WALWebOperationVm.h"
#import <Foundation/Foundation.h>
@class WALPpaWebOperationPresenter;


@protocol WALPpaWebOperationView

- (void)setPresenter:(nullable WALPpaWebOperationPresenter *)presenter;

- (void)setWebOperationVm:(nonnull WALWebOperationVm *)webOperation;

@end
