// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_access.djinni

#import <Foundation/Foundation.h>
@class WALPpaAccessPresenter;


@protocol WALPpaAccessView

- (void)setPresenter:(nullable WALPpaAccessPresenter *)presenter;

@end
