// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_credit_card_select_acquirer.djinni

#import "WALPpaPaymentMethodVm.h"
#import <Foundation/Foundation.h>


@interface WALPpaCreditCardSelectAcquirerPresenter : NSObject

- (void)selectPaymentMethod:(nonnull WALPpaPaymentMethodVm *)creditCard;

- (void)openWhyFee;

@end
