// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_unactivated_email.djinni

#import <Foundation/Foundation.h>
@class WALPpaUnactivatedEmailPresenter;


@protocol WALPpaUnactivatedEmailView

- (void)setPresenter:(nullable WALPpaUnactivatedEmailPresenter *)presenter;

@end
