// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_insert_otp.djinni

#import <Foundation/Foundation.h>
@class WALPpaInsertOtpPresenter;


@protocol WALPpaInsertOtpView

- (void)setPresenter:(nullable WALPpaInsertOtpPresenter *)presenter;

- (void)showEditPhoneNumber:(BOOL)showEditPhoneNumber;

- (void)setTopMessage:(nonnull NSString *)messageType;

@end
