// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_web_payment.djinni

#import <Foundation/Foundation.h>
@class WALPpaWebPaymentPresenter;


@protocol WALPpaWebPaymentView

- (void)setPresenter:(nullable WALPpaWebPaymentPresenter *)presenter;

- (void)setExternalLink:(nonnull NSString *)externalLink;

- (void)setCloseLink:(nonnull NSArray<NSString *> *)closeLink;

@end
