// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_recovery_change_password.djinni

#import <Foundation/Foundation.h>


@interface WALPpaRecoveryChangePasswordPresenter : NSObject

- (void)proceed:(nonnull NSString *)password;

- (void)showPasswordTooltip;

- (void)setPartialPassword:(nonnull NSString *)password;

@end
