// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_selected_bank_payment_method.djinni

#import <Foundation/Foundation.h>


@interface WALPpaSelectedBankPaymentMethodPresenter : NSObject

- (void)openWhyFee;

- (void)proceedWithRegistration;

- (void)proceedWithoutRegistration;

@end
