// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_recovery_insert_password.djinni

#import <Foundation/Foundation.h>
@class WALPpaRecoveryInsertPasswordPresenter;


@protocol WALPpaRecoveryInsertPasswordView

- (void)setPresenter:(nullable WALPpaRecoveryInsertPasswordPresenter *)presenter;

@end
