// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_external_payment.djinni

#import <Foundation/Foundation.h>


@interface WALPpaExternalPaymentPresenter : NSObject

- (void)proceed:(BOOL)rememberPaymentMethod
favoritePaymentMethod:(BOOL)favoritePaymentMethod;

@end
