// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_waiting_for_payment.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, WALPpaPaymentStatus)
{
    WALPpaPaymentStatusWaiting,
    WALPpaPaymentStatusError,
    WALPpaPaymentStatusTimedOut,
    WALPpaPaymentStatusCompleted,
};
