// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_registration_method_default.djinni

#import "WALWalletVm.h"
#import <Foundation/Foundation.h>
@class WALPpaRegistrationMethodDefaultPresenter;


@protocol WALPpaRegistrationMethodDefaultView

- (void)setPresenter:(nullable WALPpaRegistrationMethodDefaultPresenter *)presenter;

- (void)setPaymentMethod:(nonnull WALWalletVm *)paymentMethod;

@end
