// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_top_bar_vm.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, WALPpaTopBarButton)
{
    WALPpaTopBarButtonCloseButton,
    WALPpaTopBarButtonMenuButton,
};
