// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_transaction_detail.djinni

#import "WALLifecycle.h"
#import "WALTransactionVm.h"
#import "WALWalletVm.h"
#import <Foundation/Foundation.h>
@class WALPpaTransactionDetailPresenter;


@protocol WALPpaTransactionDetailView

- (void)setTransaction:(nonnull WALTransactionVm *)transaction;

- (void)setPaymentMethod:(nonnull WALWalletVm *)paymentMethod;

- (void)setPresenter:(nullable WALPpaTransactionDetailPresenter *)presenter;

- (void)setLifecycle:(nullable WALLifecycle *)lifecycle;

@end
