// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_other_payment_method_types.djinni

#import "WALPpaPaymentMethodVm.h"
#import <Foundation/Foundation.h>


@interface WALPpaOtherPaymentMethodTypesPresenter : NSObject

- (void)selectOtherPaymentMethod:(nonnull WALPpaPaymentMethodVm *)paymentMethod;

- (void)cantFindPaymentMethod;

@end
