// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_session.djinni

#import <Foundation/Foundation.h>
@protocol WALPpaSessionCallback;


@interface WALPpaSession : NSObject

- (void)startPaymentSession:(nonnull NSString *)paymentId
                   callback:(nullable id<WALPpaSessionCallback>)callback;

- (void)userClose;

@end
