// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_waiting_for_payment.djinni

#import <Foundation/Foundation.h>


@interface WALPpaWaitingForPaymentPresenter : NSObject

- (void)close;

@end
