// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_registration_step_1.djinni

#import <Foundation/Foundation.h>


@interface WALPpaRegistrationStep1Presenter : NSObject

- (void)proceed:(nonnull NSString *)name
       lastName:(nonnull NSString *)lastName;

- (void)cancel;

@end
