// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_user_removed.djinni

#import <Foundation/Foundation.h>
@class WALPpaUserRemovedPresenter;


@protocol WALPpaUserRemovedView

- (void)setPresenter:(nullable WALPpaUserRemovedPresenter *)presenter;

@end
