// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_registration_step_3.djinni

#import <Foundation/Foundation.h>


@interface WALPpaRegistrationStep3Presenter : NSObject

- (void)proceed:(nonnull NSString *)username
       password:(nonnull NSString *)password
 repeatPassword:(nonnull NSString *)repeatPassword;

- (void)setPartialPassword:(nonnull NSString *)password;

- (void)showUsernameTooltip;

- (void)showPasswordTooltip;

- (void)cancel;

@end
