// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_unactivated_email.djinni

#import <Foundation/Foundation.h>


@interface WALPpaUnactivatedEmailPresenter : NSObject

- (void)sendActivationEmail;

- (void)deleteUser;

- (void)cancel;

@end
