// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_terms.djinni

#import <Foundation/Foundation.h>
@class WALPpaTermsPresenter;


@protocol WALPpaTermsView

- (void)setPresenter:(nullable WALPpaTermsPresenter *)presenter;

- (void)setTerms:(nonnull NSString *)terms;

- (void)setContinueButtonEnabledStatus:(BOOL)enabled;

@end
