// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_confirm_credit_card_payment.djinni

#import <Foundation/Foundation.h>


@interface WALPpaConfirmCreditCardPaymentPresenter : NSObject

- (void)openWhyFee;

- (void)confirmPayment;

- (void)editAcquirer;

@end
