// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_saved_payment_methods.djinni

#import "WALWalletVm.h"
#import <Foundation/Foundation.h>
@class WALPpaSavedPaymentMethodsPresenter;


@protocol WALPpaSavedPaymentMethodsView

- (void)setPresenter:(nullable WALPpaSavedPaymentMethodsPresenter *)presenter;

- (void)setPaymentMethods:(nonnull NSArray<WALWalletVm *> *)paymentMethods;

@end
