// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_error_payment.djinni

#import <Foundation/Foundation.h>
@class WALPpaErrorPaymentPresenter;


@protocol WALPpaErrorPaymentView

- (void)setPresenter:(nullable WALPpaErrorPaymentPresenter *)presenter;

@end
