// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_routes.djinni

#import <Foundation/Foundation.h>

@interface WALPpaRoutes : NSObject
- (nonnull instancetype)init;
+ (nonnull instancetype)ppaRoutes;

@end

extern NSString * __nonnull const WALPpaRoutesRoutePpaBase;
extern NSString * __nonnull const WALPpaRoutesRoutePpaLoading;
extern NSString * __nonnull const WALPpaRoutesRoutePpaAccess;
extern NSString * __nonnull const WALPpaRoutesRoutePpaAccessEmail;
extern NSString * __nonnull const WALPpaRoutesRoutePpaAccessPassword;
extern NSString * __nonnull const WALPpaRoutesRoutePpaAccessRegisteredSpid;
extern NSString * __nonnull const WALPpaRoutesRoutePpaAccessSpidProviderSelection;
extern NSString * __nonnull const WALPpaRoutesRoutePpaAccessTerms;
extern NSString * __nonnull const WALPpaRoutesRoutePpaPaymentMethodTypes;
extern NSString * __nonnull const WALPpaRoutesRoutePpaOtherPaymentMethodTypes;
extern NSString * __nonnull const WALPpaRoutesRoutePpaPaymentMethodDetail;
extern NSString * __nonnull const WALPpaRoutesRoutePpaTransactionsList;
extern NSString * __nonnull const WALPpaRoutesRoutePpaTransactionDetail;
extern NSString * __nonnull const WALPpaRoutesRoutePpaAddCreditCard;
extern NSString * __nonnull const WALPpaRoutesRoutePpaConfirmCreditCardPayment;
extern NSString * __nonnull const WALPpaRoutesRoutePpaUnregisteredPaymentCompleted;
extern NSString * __nonnull const WALPpaRoutesRoutePpaPaymentCompleted;
extern NSString * __nonnull const WALPpaRoutesRoutePpaSelectBankPaymentMethod;
extern NSString * __nonnull const WALPpaRoutesRoutePpaExternalPayment;
extern NSString * __nonnull const WALPpaRoutesRoutePpaWebOperation;
extern NSString * __nonnull const WALPpaRoutesRoutePpaWaitingForPayment;
extern NSString * __nonnull const WALPpaRoutesRoutePpaCreditCardSelectAcquirer;
extern NSString * __nonnull const WALPpaRoutesRoutePpaSelectedBankPaymentMethod;
extern NSString * __nonnull const WALPpaRoutesRoutePpaUserMenu;
extern NSString * __nonnull const WALPpaRoutesRoutePpaSavedPaymentMethods;
extern NSString * __nonnull const WALPpaRoutesRoutePpaInsertOtp;
extern NSString * __nonnull const WALPpaRoutesRoutePpaRegistrationStep1;
extern NSString * __nonnull const WALPpaRoutesRoutePpaRegistrationStep2;
extern NSString * __nonnull const WALPpaRoutesRoutePpaRegistrationStep3;
extern NSString * __nonnull const WALPpaRoutesRoutePpaRegistrationCompletedCreditCard;
extern NSString * __nonnull const WALPpaRoutesRoutePpaRegistrationCompletedBank;
extern NSString * __nonnull const WALPpaRoutesRoutePpaRegistrationMethodCreditCardSaved;
extern NSString * __nonnull const WALPpaRoutesRoutePpaRegistrationMethodBankSaved;
extern NSString * __nonnull const WALPpaRoutesRoutePpaRegistrationMethodDefault;
extern NSString * __nonnull const WALPpaRoutesRoutePpaTopBar;
extern NSString * __nonnull const WALPpaRoutesRoutePpaChangePhoneNumber;
extern NSString * __nonnull const WALPpaRoutesRoutePpaInsertSecretCode;
extern NSString * __nonnull const WALPpaRoutesRoutePpaRecoveryInsertPassword;
extern NSString * __nonnull const WALPpaRoutesRoutePpaRecoveryChangePassword;
extern NSString * __nonnull const WALPpaRoutesRoutePpaRecoveryResult;
extern NSString * __nonnull const WALPpaRoutesRoutePpaConfirmResetPassword;
extern NSString * __nonnull const WALPpaRoutesRoutePpaUnactivatedEmail;
extern NSString * __nonnull const WALPpaRoutesRoutePpaEmailSent;
extern NSString * __nonnull const WALPpaRoutesRoutePpaUserRemoved;
extern NSString * __nonnull const WALPpaRoutesRoutePpaModifyEmail;
extern NSString * __nonnull const WALPpaRoutesRoutePpaWebPayment;
extern NSString * __nonnull const WALPpaRoutesRoutePpaErrorPayment;
