// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_recovery_result.djinni

#import <Foundation/Foundation.h>


@interface WALPpaRecoveryResultPresenter : NSObject

- (void)proceed:(BOOL)success;

@end
