// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_change_phone_number.djinni

#import <Foundation/Foundation.h>
@class WALPpaChangePhoneNumberPresenter;


@protocol WALPpaChangePhoneNumberView

- (void)setChangePhoneNumberPresenter:(nullable WALPpaChangePhoneNumberPresenter *)presenter;

@end
