// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_top_bar_vm.djinni

#import "WALPpaTopBarButton.h"
#import <Foundation/Foundation.h>

@interface WALPpaTopBarVm : NSObject
- (nonnull instancetype)initWithFirstLine:(nonnull NSString *)firstLine
                               secondLine:(nonnull NSString *)secondLine
                                thirdLine:(nonnull NSString *)thirdLine
                         rightButtonStyle:(WALPpaTopBarButton)rightButtonStyle;
+ (nonnull instancetype)ppaTopBarVmWithFirstLine:(nonnull NSString *)firstLine
                                      secondLine:(nonnull NSString *)secondLine
                                       thirdLine:(nonnull NSString *)thirdLine
                                rightButtonStyle:(WALPpaTopBarButton)rightButtonStyle;

@property (nonatomic, readonly, nonnull) NSString * firstLine;

@property (nonatomic, readonly, nonnull) NSString * secondLine;

@property (nonatomic, readonly, nonnull) NSString * thirdLine;

@property (nonatomic, readonly) WALPpaTopBarButton rightButtonStyle;

@end
