// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_unregistered_payment_completed.djinni

#import <Foundation/Foundation.h>


@interface WALPpaUnregisteredPaymentCompletedPresenter : NSObject

- (void)openRegistration;

- (void)close;

@end
