// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_insert_password.djinni

#import <Foundation/Foundation.h>


@interface WALPpaInsertPasswordPresenter : NSObject

- (void)openAccountRecovery;

- (void)showUsernameTooltip;

- (void)showPasswordTooltip;

- (void)proceed:(nonnull NSString *)username
       password:(nonnull NSString *)password;

@end
