// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_other_payment_method_types.djinni

#import "WALPpaPaymentMethodVm.h"
#import <Foundation/Foundation.h>
@class WALPpaOtherPaymentMethodTypesPresenter;


@protocol WALPpaOtherPaymentMethodTypesView

- (void)setPresenter:(nullable WALPpaOtherPaymentMethodTypesPresenter *)presenter;

- (void)setPaymentMethods:(nonnull NSArray<WALPpaPaymentMethodVm *> *)paymentMethods;

@end
