// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_session.djinni

#import "WALPpaPaymentVm.h"
#import <Foundation/Foundation.h>


@protocol WALPpaSessionCallback

- (void)onPaymentCompleted:(nonnull WALPpaPaymentVm *)payment;

- (void)onPaymentFailed;

- (void)onPaymentAbortedByUser;

@end
