// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_recovery_insert_password.djinni

#import <Foundation/Foundation.h>


@interface WALPpaRecoveryInsertPasswordPresenter : NSObject

- (void)openAccountRecovery;

- (void)proceed:(nonnull NSString *)password;

@end
