// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_registration_step_2.djinni

#import <Foundation/Foundation.h>


@interface WALPpaRegistrationStep2Presenter : NSObject

- (void)proceed:(nonnull NSString *)phoneNumber;

- (void)cancel;

@end
