// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_payment_method_vm.djinni

#import "WALPpaWalletType.h"
#import <Foundation/Foundation.h>

@interface WALPpaPaymentMethodVm : NSObject
- (nonnull instancetype)initWithId:(int64_t)id
                             idPsp:(nonnull NSString *)idPsp
                      businessName:(nonnull NSString *)businessName
                       paymentType:(WALPpaWalletType)paymentType
                    idIntermediary:(nonnull NSString *)idIntermediary
                         idChannel:(nonnull NSString *)idChannel
                           logoPSP:(nonnull NSString *)logoPSP
                       serviceLogo:(nonnull NSString *)serviceLogo
                       serviceName:(nonnull NSString *)serviceName
                         fixedCost:(nonnull NSString *)fixedCost
                        appChannel:(BOOL)appChannel
                serviceDescription:(nonnull NSString *)serviceDescription
               serviceAvailability:(nonnull NSString *)serviceAvailability
                    urlInfoChannel:(nonnull NSString *)urlInfoChannel
                      paymentModel:(int64_t)paymentModel;
+ (nonnull instancetype)ppaPaymentMethodVmWithId:(int64_t)id
                                           idPsp:(nonnull NSString *)idPsp
                                    businessName:(nonnull NSString *)businessName
                                     paymentType:(WALPpaWalletType)paymentType
                                  idIntermediary:(nonnull NSString *)idIntermediary
                                       idChannel:(nonnull NSString *)idChannel
                                         logoPSP:(nonnull NSString *)logoPSP
                                     serviceLogo:(nonnull NSString *)serviceLogo
                                     serviceName:(nonnull NSString *)serviceName
                                       fixedCost:(nonnull NSString *)fixedCost
                                      appChannel:(BOOL)appChannel
                              serviceDescription:(nonnull NSString *)serviceDescription
                             serviceAvailability:(nonnull NSString *)serviceAvailability
                                  urlInfoChannel:(nonnull NSString *)urlInfoChannel
                                    paymentModel:(int64_t)paymentModel;

@property (nonatomic, readonly) int64_t id;

@property (nonatomic, readonly, nonnull) NSString * idPsp;

@property (nonatomic, readonly, nonnull) NSString * businessName;

@property (nonatomic, readonly) WALPpaWalletType paymentType;

@property (nonatomic, readonly, nonnull) NSString * idIntermediary;

@property (nonatomic, readonly, nonnull) NSString * idChannel;

@property (nonatomic, readonly, nonnull) NSString * logoPSP;

@property (nonatomic, readonly, nonnull) NSString * serviceLogo;

@property (nonatomic, readonly, nonnull) NSString * serviceName;

@property (nonatomic, readonly, nonnull) NSString * fixedCost;

@property (nonatomic, readonly) BOOL appChannel;

@property (nonatomic, readonly, nonnull) NSString * serviceDescription;

@property (nonatomic, readonly, nonnull) NSString * serviceAvailability;

@property (nonatomic, readonly, nonnull) NSString * urlInfoChannel;

@property (nonatomic, readonly) int64_t paymentModel;

@end
