// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_modify_email.djinni

#import <Foundation/Foundation.h>
@class WALPpaModifyEmailPresenter;


@protocol WALPpaModifyEmailView

- (void)setPresenter:(nullable WALPpaModifyEmailPresenter *)presenter;

@end
