// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_views_builder.djinni

#import "WALUiRouteInformation.h"
#import <Foundation/Foundation.h>
@protocol WALPpaAccessView;
@protocol WALPpaAddCreditCardView;
@protocol WALPpaChangePhoneNumberView;
@protocol WALPpaConfirmCreditCardPaymentView;
@protocol WALPpaConfirmResetPasswordView;
@protocol WALPpaCreditCardSelectAcquirerView;
@protocol WALPpaExternalPaymentView;
@protocol WALPpaInsertEmailView;
@protocol WALPpaInsertOtpView;
@protocol WALPpaInsertPasswordView;
@protocol WALPpaInsertSecretCodeView;
@protocol WALPpaLoadingView;
@protocol WALPpaOtherPaymentMethodTypesView;
@protocol WALPpaPaymentCompletedView;
@protocol WALPpaPaymentMethodTypesView;
@protocol WALPpaRecoveryChangePasswordView;
@protocol WALPpaRecoveryInsertPasswordView;
@protocol WALPpaRecoveryResultView;
@protocol WALPpaRegistrationCompletedBankView;
@protocol WALPpaRegistrationCompletedCreditCardView;
@protocol WALPpaRegistrationMethodBankSavedView;
@protocol WALPpaRegistrationMethodCreditCardSavedView;
@protocol WALPpaRegistrationMethodDefaultView;
@protocol WALPpaRegistrationStep1View;
@protocol WALPpaRegistrationStep2View;
@protocol WALPpaRegistrationStep3View;
@protocol WALPpaSavedPaymentMethodsView;
@protocol WALPpaSelectBankPaymentMethodView;
@protocol WALPpaSelectedBankPaymentMethodView;
@protocol WALPpaTermsView;
@protocol WALPpaTopBarView;
@protocol WALPpaTransactionDetailView;
@protocol WALPpaTransactionsListView;
@protocol WALPpaUnregisteredPaymentCompletedView;
@protocol WALPpaUserMenuView;
@protocol WALPpaWaitingForPaymentView;
@protocol WALPpaWebOperationView;


@protocol WALPpaViewsBuilder

- (nullable id<WALPpaTransactionsListView>)openPpaTransactionsListView:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaAccessView>)openPpaAccessView:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaInsertEmailView>)openPpaInsertEmailView:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaInsertPasswordView>)openPpaInsertPasswordView:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaTermsView>)openPpaTermsView:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaPaymentMethodTypesView>)openPpaPaymentMethodTypes:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaOtherPaymentMethodTypesView>)openPpaOtherPaymentMethodTypes:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaAddCreditCardView>)openPpaAddCreditCard:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaSelectedBankPaymentMethodView>)openPpaSelectedBankPaymentMethod:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaUserMenuView>)openPpaUserMenu:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaRegistrationStep1View>)openPpaRegistrationStep1:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaRegistrationStep2View>)openPpaRegistrationStep2:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaRegistrationStep3View>)openPpaRegistrationStep3:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaRegistrationCompletedCreditCardView>)openPpaRegistrationCompletedCreditCard:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaRegistrationCompletedBankView>)openPpaRegistrationCompletedBank:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaRegistrationMethodCreditCardSavedView>)openPpaRegistrationMethodCreditCardSaved:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaRegistrationMethodBankSavedView>)openPpaRegistrationMethodBankSaved:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaRegistrationMethodDefaultView>)openPpaRegistrationMethodDefault:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaExternalPaymentView>)openPpaExternalPayment:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaWebOperationView>)openPpaWebOperation:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaWaitingForPaymentView>)openPpaWaitingForPayment:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaCreditCardSelectAcquirerView>)openPpaCreditCardSelectAcquirer:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaSelectBankPaymentMethodView>)openPpaSelectBankPaymentMethod:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaConfirmCreditCardPaymentView>)openPpaConfirmCreditCardPayment:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaLoadingView>)openPpaLoading:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaPaymentCompletedView>)openPpaPaymentCompleted:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaTransactionDetailView>)openPpaTransactionDetail:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaUnregisteredPaymentCompletedView>)openPpaUnregisteredPaymentCompleted:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaSavedPaymentMethodsView>)openPpaSavedPaymentMethods:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaInsertOtpView>)openPpaInsertOtp:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaTopBarView>)openPpaTopBar:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaChangePhoneNumberView>)openPpaChangePhoneNumber:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaInsertSecretCodeView>)openPpaInsertSecretCode:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaRecoveryInsertPasswordView>)openPpaRecoveryInsertPassword:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaRecoveryChangePasswordView>)openPpaRecoveryChangePassword:(nonnull WALUiRouteInformation *)uiRouteInformation;

- (nullable id<WALPpaRecoveryResultView>)openPpaRecoveryResult:(nonnull WALUiRouteInformation *)iRouteInformation;

- (nullable id<WALPpaConfirmResetPasswordView>)openPpaConfirmResetPassword:(nonnull WALUiRouteInformation *)iRouteInformation;

@end
