// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_user_menu.djinni

#import <Foundation/Foundation.h>


@interface WALPpaUserMenuPresenter : NSObject

- (void)openSavedPaymentMethods;

- (void)openTransactionsHistory;

- (void)openEditPhoneNumber;

- (void)openEditEmailAddress;

- (void)openMergeSpid;

- (void)openFavoritePsp;

- (void)logout;

- (void)cancelPayment;

- (void)closeMenu;

@end
