// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_terms.djinni

#import <Foundation/Foundation.h>


@interface WALPpaTermsPresenter : NSObject

- (void)setAcceptConditions:(BOOL)accept;

- (void)setAcceptPrivacy:(BOOL)accept;

- (void)proceed;

@end
