// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_registration_step_3.djinni

#import "WALPpaPasswordStrengthVm.h"
#import "WALPpaWalletType.h"
#import <Foundation/Foundation.h>
@class WALPpaRegistrationStep3Presenter;


@protocol WALPpaRegistrationStep3View

- (void)setPresenter:(nullable WALPpaRegistrationStep3Presenter *)presenter;

- (void)setPasswordStrength:(nonnull WALPpaPasswordStrengthVm *)passwordStrength;

- (void)setPaymentType:(WALPpaWalletType)walletType;

@end
