// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_wallet_type.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, WALPpaWalletType)
{
    WALPpaWalletTypeCreditCard,
    WALPpaWalletTypeBankAccount,
    WALPpaWalletTypeExternalPs,
    WALPpaWalletTypeUnknown,
};
