// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_loading_status.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, WALPpaLoadingStatus)
{
    WALPpaLoadingStatusChecking,
    WALPpaLoadingStatusSecure,
};
