// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_external_payment.djinni

#import "WALPpaExternalPaymentVm.h"
#import <Foundation/Foundation.h>
@class WALPpaExternalPaymentPresenter;


@protocol WALPpaExternalPaymentView

- (void)setPresenter:(nullable WALPpaExternalPaymentPresenter *)presenter;

/** show or hide the "remember this payment method" checkbox */
- (void)showRememberCheckbox:(BOOL)showRememberCheckbox;

- (void)setExternalPaymentMethod:(nonnull WALPpaExternalPaymentVm *)paymentMethod;

@end
