// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_add_credit_card.djinni

#import <Foundation/Foundation.h>
@class WALPpaAddCreditCardPresenter;


@protocol WALPpaAddCreditCardView

- (void)setPanImageUrl:(nonnull NSString *)panImageUrl;

- (void)setPresenter:(nullable WALPpaAddCreditCardPresenter *)presenter;

@end
