// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_confirm_reset_password.djinni

#import <Foundation/Foundation.h>


@interface WALPpaConfirmResetPasswordPresenter : NSObject

- (void)confirm;

@end
