// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_change_phone_number.djinni

#import <Foundation/Foundation.h>


@interface WALPpaChangePhoneNumberPresenter : NSObject

- (void)proceed:(nonnull NSString *)phoneNumber;

@end
