// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_registration_step_2.djinni

#import "WALPpaWalletType.h"
#import <Foundation/Foundation.h>
@class WALPpaRegistrationStep2Presenter;


@protocol WALPpaRegistrationStep2View

- (void)setPresenter:(nullable WALPpaRegistrationStep2Presenter *)presenter;

- (void)setPaymentType:(WALPpaWalletType)walletType;

@end
