// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_insert_email.djinni

#import <Foundation/Foundation.h>


@interface WALPpaInsertEmailPresenter : NSObject

- (void)proceed:(nonnull NSString *)email;

@end
