// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_payment_method_types.djinni

#import "WALPpaPaymentMethodTypeVm.h"
#import <Foundation/Foundation.h>
@class WALPpaPaymentMethodTypesPresenter;


@protocol WALPpaPaymentMethodTypesView

- (void)setPresenter:(nullable WALPpaPaymentMethodTypesPresenter *)presenter;

- (void)setMethodsFee:(nonnull WALPpaPaymentMethodTypeVm *)paymentMethodsFee;

@end
