// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_recovery_result.djinni

#import <Foundation/Foundation.h>
@class WALPpaRecoveryResultPresenter;


@protocol WALPpaRecoveryResultView

- (void)setPresenter:(nullable WALPpaRecoveryResultPresenter *)presenter;

- (void)setType:(nonnull NSString *)type;

- (void)setChangeSuccessful:(BOOL)success;

- (void)setUsername:(nonnull NSString *)username;

@end
