// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_payment_completed.djinni

#import <Foundation/Foundation.h>
@class WALPpaPaymentCompletedPresenter;


@protocol WALPpaPaymentCompletedView

- (void)setEmail:(nonnull NSString *)email;

- (void)setName:(nonnull NSString *)text;

/** show or hide the "remember this payment method" checkbox */
- (void)showRememberCheckbox:(BOOL)showRememberCheckbox;

- (void)setPresenter:(nullable WALPpaPaymentCompletedPresenter *)presenter;

@end
