// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_transaction_detail.djinni

#import <Foundation/Foundation.h>


@interface WALPpaTransactionDetailPresenter : NSObject

- (void)refresh;

@end
