// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_user_menu.djinni

#import <Foundation/Foundation.h>
@class WALPpaUserMenuPresenter;


@protocol WALPpaUserMenuView

- (void)setPresenter:(nullable WALPpaUserMenuPresenter *)presenter;

- (void)setUserName:(nonnull NSString *)username;

@end
