// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_web_operation.djinni

#import <Foundation/Foundation.h>


@interface WALPpaWebOperationPresenter : NSObject

- (void)webOperationCompletedCallback;

- (void)webOperationErrorCallback;

- (void)webOperationCancelledCallback;

@end
