// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_transactions_list.djinni

#import "WALTransactionVm.h"
#import <Foundation/Foundation.h>
@class WALPpaTransactionsListPresenter;


@protocol WALPpaTransactionsListView

- (void)refreshTransactionsList:(nonnull NSArray<WALTransactionVm *> *)transactions;

- (void)setPresenter:(nullable WALPpaTransactionsListPresenter *)presenter;

@end
