// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_insert_otp.djinni

#import <Foundation/Foundation.h>


@interface WALPpaInsertOtpPresenter : NSObject

- (void)editPhoneNumber;

- (void)sendNewOtp;

- (void)proceed:(nonnull NSString *)otp;

@end
