// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_select_bank_payment_method.djinni

#import "WALPpaPaymentMethodVm.h"
#import <Foundation/Foundation.h>


@interface WALPpaSelectBankPaymentMethodPresenter : NSObject

- (void)searchPaymentMethod:(nonnull NSString *)query;

- (void)selectPaymentMethod:(nonnull WALPpaPaymentMethodVm *)bank;

- (void)openCantFindBank;

@end
