// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_payment_completed.djinni

#import <Foundation/Foundation.h>


@interface WALPpaPaymentCompletedPresenter : NSObject

- (void)openTransactionsList:(BOOL)rememberPaymentMethod
       favoritePaymentMethod:(BOOL)favoritePaymentMethod;

- (void)close:(BOOL)rememberPaymentMethod
favoritePaymentMethod:(BOOL)favoritePaymentMethod;

@end
