// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_external_payment_vm.djinni

#import <Foundation/Foundation.h>

@interface WALPpaExternalPaymentVm : NSObject
- (nonnull instancetype)initWithLogoUrl:(nonnull NSString *)logoUrl
                                    fee:(nonnull NSString *)fee
                        additionalText1:(nonnull NSString *)additionalText1;
+ (nonnull instancetype)ppaExternalPaymentVmWithLogoUrl:(nonnull NSString *)logoUrl
                                                    fee:(nonnull NSString *)fee
                                        additionalText1:(nonnull NSString *)additionalText1;

@property (nonatomic, readonly, nonnull) NSString * logoUrl;

@property (nonatomic, readonly, nonnull) NSString * fee;

@property (nonatomic, readonly, nonnull) NSString * additionalText1;

@end
