// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_registration_completed_bank.djinni

#import "WALPpaRegistrationCompletedDataVm.h"
#import <Foundation/Foundation.h>
@class WALPpaRegistrationCompletedBankPresenter;


@protocol WALPpaRegistrationCompletedBankView

- (void)setBankPresenter:(nullable WALPpaRegistrationCompletedBankPresenter *)presenter;

- (void)setRegistrationCompletedData:(nonnull WALPpaRegistrationCompletedDataVm *)registrationCompletedData;

@end
