// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_add_credit_card.djinni

#import "WALCreditCardVm.h"
#import <Foundation/Foundation.h>


@interface WALPpaAddCreditCardPresenter : NSObject

- (void)openCamera;

- (void)setPartialPan:(nonnull NSString *)pan;

- (void)proceed:(nonnull WALCreditCardVm *)creditCard;

@end
