// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_payment_vm.djinni

#import <Foundation/Foundation.h>

@interface WALPpaPaymentVm : NSObject
- (nonnull instancetype)initWithEmail:(nonnull NSString *)email
                                 name:(nonnull NSString *)name
                               amount:(nonnull NSString *)amount
                             receiver:(nonnull NSString *)receiver
                              subject:(nonnull NSString *)subject;
+ (nonnull instancetype)ppaPaymentVmWithEmail:(nonnull NSString *)email
                                         name:(nonnull NSString *)name
                                       amount:(nonnull NSString *)amount
                                     receiver:(nonnull NSString *)receiver
                                      subject:(nonnull NSString *)subject;

@property (nonatomic, readonly, nonnull) NSString * email;

@property (nonatomic, readonly, nonnull) NSString * name;

@property (nonatomic, readonly, nonnull) NSString * amount;

@property (nonatomic, readonly, nonnull) NSString * receiver;

@property (nonatomic, readonly, nonnull) NSString * subject;

@end
