// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_insert_secret_code.djinni

#import <Foundation/Foundation.h>
@class WALPpaInsertSecretCodePresenter;


@protocol WALPpaInsertSecretCodeView

- (void)setPresenter:(nullable WALPpaInsertSecretCodePresenter *)presenter;

@end
