// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_insert_email.djinni

#import <Foundation/Foundation.h>
@class WALPpaInsertEmailPresenter;


@protocol WALPpaInsertEmailView

- (void)setPresenter:(nullable WALPpaInsertEmailPresenter *)presenter;

@end
