// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_transactions_list.djinni

#import "WALTransactionVm.h"
#import <Foundation/Foundation.h>


@interface WALPpaTransactionsListPresenter : NSObject

- (void)openTransactionDetail:(nonnull WALTransactionVm *)transaction;

- (void)searchTransactions:(nonnull NSString *)query;

- (void)openCantFindTransactions;

- (void)refreshTransactions;

@end
