// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_recovery_change_password.djinni

#import "WALPpaPasswordStrengthVm.h"
#import <Foundation/Foundation.h>
@class WALPpaRecoveryChangePasswordPresenter;


@protocol WALPpaRecoveryChangePasswordView

- (void)setChangePasswordPresenter:(nullable WALPpaRecoveryChangePasswordPresenter *)presenter;

- (void)setPasswordStrength:(nonnull WALPpaPasswordStrengthVm *)passwordStrength;

- (void)setEmail:(nonnull NSString *)email;

@end
