// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_selected_bank_payment_method.djinni

#import "WALPpaPaymentMethodVm.h"
#import <Foundation/Foundation.h>
@class WALPpaSelectedBankPaymentMethodPresenter;


@protocol WALPpaSelectedBankPaymentMethodView

- (void)setPresenter:(nullable WALPpaSelectedBankPaymentMethodPresenter *)presenter;

- (void)setSelectedBankPaymentMethodVm:(nonnull WALPpaPaymentMethodVm *)selectedBankPaymentMethodVm;

@end
