// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_registration_method_bank_saved.djinni

#import <Foundation/Foundation.h>


@interface WALPpaRegistrationMethodBankSavedPresenter : NSObject

- (void)setDefaultPaymentMethod;

- (void)goToPayment;

@end
