// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_registration_completed_credit_card.djinni

#import "WALPpaRegistrationCompletedDataVm.h"
#import <Foundation/Foundation.h>
@class WALPpaRegistrationCompletedCreditCardPresenter;


@protocol WALPpaRegistrationCompletedCreditCardView

- (void)setCreditCardPresenter:(nullable WALPpaRegistrationCompletedCreditCardPresenter *)presenter;

- (void)setRegistrationCompletedData:(nonnull WALPpaRegistrationCompletedDataVm *)registrationCompletedData;

@end
