// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_registration_completed_credit_card.djinni

#import <Foundation/Foundation.h>


@interface WALPpaRegistrationCompletedCreditCardPresenter : NSObject

- (void)changeEmailAddress;

- (void)savePaymentMethod;

- (void)cancel;

@end
