// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_registration_completed_data_vm.djinni

#import "WALPpaWalletType.h"
#import <Foundation/Foundation.h>

@interface WALPpaRegistrationCompletedDataVm : NSObject
- (nonnull instancetype)initWithPin:(nonnull NSString *)pin
                               mail:(nonnull NSString *)mail
                               name:(nonnull NSString *)name
                         walletType:(WALPpaWalletType)walletType;
+ (nonnull instancetype)ppaRegistrationCompletedDataVmWithPin:(nonnull NSString *)pin
                                                         mail:(nonnull NSString *)mail
                                                         name:(nonnull NSString *)name
                                                   walletType:(WALPpaWalletType)walletType;

@property (nonatomic, readonly, nonnull) NSString * pin;

@property (nonatomic, readonly, nonnull) NSString * mail;

@property (nonatomic, readonly, nonnull) NSString * name;

@property (nonatomic, readonly) WALPpaWalletType walletType;

@end
