// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_access.djinni

#import <Foundation/Foundation.h>


@interface WALPpaAccessPresenter : NSObject

- (void)openSpidAccess;

- (void)openNoSpid;

- (void)openWhatIsSpid;

- (void)openEmailAccess;

@end
