// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_email_sent.djinni

#import <Foundation/Foundation.h>
@class WALPpaEmailSentPresenter;


@protocol WALPpaEmailSentView

- (void)setPresenter:(nullable WALPpaEmailSentPresenter *)presenter;

@end
