// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_registration_method_credit_card_saved.djinni

#import "WALWalletVm.h"
#import <Foundation/Foundation.h>
@class WALPpaRegistrationMethodCreditCardSavedPresenter;


@protocol WALPpaRegistrationMethodCreditCardSavedView

- (void)setCreditCardPresenter:(nullable WALPpaRegistrationMethodCreditCardSavedPresenter *)presenter;

- (void)setPaymentMethod:(nonnull WALWalletVm *)creditCard;

@end
