// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_confirm_credit_card_payment.djinni

#import "WALWalletVm.h"
#import <Foundation/Foundation.h>
@class WALPpaConfirmCreditCardPaymentPresenter;


@protocol WALPpaConfirmCreditCardPaymentView

- (void)setCreditCard:(nonnull WALWalletVm *)creditCard;

- (void)setFee:(nonnull NSString *)fee;

- (void)setEmail:(nonnull NSString *)email;

- (void)setTotal:(nonnull NSString *)total;

- (void)showEditAcquirerButton:(BOOL)showEditAcquirerButton
                    pspLogoUrl:(nonnull NSString *)pspLogoUrl;

- (void)setPresenter:(nullable WALPpaConfirmCreditCardPaymentPresenter *)presenter;

@end
