// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_unregistered_payment_completed.djinni

#import <Foundation/Foundation.h>
@class WALPpaUnregisteredPaymentCompletedPresenter;


@protocol WALPpaUnregisteredPaymentCompletedView

- (void)setEmail:(nonnull NSString *)email;

- (void)setName:(nonnull NSString *)name;

- (void)setPresenter:(nullable WALPpaUnregisteredPaymentCompletedPresenter *)presenter;

@end
