// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_insert_password.djinni

#import <Foundation/Foundation.h>
@class WALPpaInsertPasswordPresenter;


@protocol WALPpaInsertPasswordView

- (void)setPresenter:(nullable WALPpaInsertPasswordPresenter *)presenter;

@end
