// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_credit_card_select_acquirer.djinni

#import "WALPpaPaymentMethodVm.h"
#import "WALWalletVm.h"
#import <Foundation/Foundation.h>
@class WALPpaCreditCardSelectAcquirerPresenter;


@protocol WALPpaCreditCardSelectAcquirerView

- (void)setPresenter:(nullable WALPpaCreditCardSelectAcquirerPresenter *)presenter;

- (void)setAvailablePaymentMethods:(nonnull NSArray<WALPpaPaymentMethodVm *> *)availableCreditCards;

- (void)setCreditCard:(nonnull WALWalletVm *)creditCard;

@end
