// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_registration_method_bank_saved.djinni

#import "WALWalletVm.h"
#import <Foundation/Foundation.h>
@class WALPpaRegistrationMethodBankSavedPresenter;


@protocol WALPpaRegistrationMethodBankSavedView

- (void)setBankPresenter:(nullable WALPpaRegistrationMethodBankSavedPresenter *)presenter;

- (void)setPaymentMethod:(nonnull WALWalletVm *)paymentMethod;

@end
