// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_confirm_reset_password.djinni

#import <Foundation/Foundation.h>
@class WALPpaConfirmResetPasswordPresenter;


@protocol WALPpaConfirmResetPasswordView

- (void)setPresenter:(nullable WALPpaConfirmResetPasswordPresenter *)presenter;

@end
