// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_registration_completed_bank.djinni

#import <Foundation/Foundation.h>


@interface WALPpaRegistrationCompletedBankPresenter : NSObject

- (void)changeEmailAddress;

- (void)savePaymentMethod;

- (void)proceed;

@end
