// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from preferences.djinni

#import <Foundation/Foundation.h>


@protocol WALPreferences

- (void)storeBoolean:(nonnull NSString *)key
               value:(BOOL)value;

- (void)storeInteger:(nonnull NSString *)key
               value:(int32_t)value;

- (void)storeLong:(nonnull NSString *)key
            value:(int64_t)value;

- (void)storeFloat:(nonnull NSString *)key
             value:(float)value;

- (void)storeString:(nonnull NSString *)key
              value:(nonnull NSString *)value;

- (void)storeDate:(nonnull NSString *)key
            value:(nonnull NSDate *)value;

- (BOOL)getBoolean:(nonnull NSString *)key;

- (int32_t)getInteger:(nonnull NSString *)key;

- (int64_t)getLong:(nonnull NSString *)key;

- (float)getFloat:(nonnull NSString *)key;

- (nonnull NSString *)getString:(nonnull NSString *)key;

- (nonnull NSDate *)getDate:(nonnull NSString *)key;

- (void)remove:(nonnull NSString *)key;

@end
