// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_loading.djinni

#import "WALPpaLoadingStatus.h"
#import <Foundation/Foundation.h>
@class WALPpaLoadingPresenter;


@protocol WALPpaLoadingView

- (void)setPresenter:(nullable WALPpaLoadingPresenter *)presenter;

- (void)setLoadingStatus:(WALPpaLoadingStatus)status;

@end
