// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_top_bar.djinni

#import "WALPpaTopBarVm.h"
#import <Foundation/Foundation.h>
@class WALPpaTopBarPresenter;


@protocol WALPpaTopBarView

- (void)setPresenter:(nullable WALPpaTopBarPresenter *)presenter;

- (void)setTopBarVm:(nonnull WALPpaTopBarVm *)barVm;

@end
