// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_payment_method_types.djinni

#import <Foundation/Foundation.h>


@interface WALPpaPaymentMethodTypesPresenter : NSObject

- (void)openAddCreditCard;

- (void)openAddBankAccount;

- (void)openOtherPaymentMethods;

- (void)openWhyFee;

@end
