// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ppa_registration_method_credit_card_saved.djinni

#import <Foundation/Foundation.h>


@interface WALPpaRegistrationMethodCreditCardSavedPresenter : NSObject

- (void)setDefaultPaymentMethod;

- (void)close;

@end
