// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui_router.djinni

#import "WALUiRoutePresentationMode.h"
#import <Foundation/Foundation.h>

@interface WALRouteInformation : NSObject
- (nonnull instancetype)initWithPath:(nonnull NSString *)path
                        presentation:(WALUiRoutePresentationMode)presentation;
+ (nonnull instancetype)routeInformationWithPath:(nonnull NSString *)path
                                    presentation:(WALUiRoutePresentationMode)presentation;

@property (nonatomic, readonly, nonnull) NSString * path;

@property (nonatomic, readonly) WALUiRoutePresentationMode presentation;

@end
