// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from resume_request_vm.djinni

#import <Foundation/Foundation.h>

@interface WALResumeRequestVm : NSObject
- (nonnull instancetype)initWithEsito:(nonnull NSString *)esito;
+ (nonnull instancetype)resumeRequestVmWithEsito:(nonnull NSString *)esito;

@property (nonatomic, readonly, nonnull) NSString * esito;

@end
