// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from core.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, WALRouterType)
{
    WALRouterTypeRoot,
    WALRouterTypeMain,
    WALRouterTypeDetail,
    WALRouterTypeTopBar,
    WALRouterTypeBottomBar,
    WALRouterTypeCustom,
    WALRouterTypeCustom2,
    WALRouterTypeCustom3,
};
