// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from thread.djinni

#import <Foundation/Foundation.h>
@class WALAsyncTask;


@protocol WALThreadLauncher

/** name is nullable */
- (void)startThread:(nullable NSString *)name
              runFn:(nullable WALAsyncTask *)runFn;

@end
