// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui_router.djinni

#import <Foundation/Foundation.h>


@interface WALUiAlertCallback : NSObject

- (void)onAlertButtonPressed:(int32_t)buttonIndex;

@end
