// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user_vm.djinni

#import <Foundation/Foundation.h>

@interface WALUserVm : NSObject
- (nonnull instancetype)initWithName:(nonnull NSString *)name
                             surname:(nonnull NSString *)surname
                               email:(nonnull NSString *)email
                           cellphone:(nonnull NSString *)cellphone;
+ (nonnull instancetype)userVmWithName:(nonnull NSString *)name
                               surname:(nonnull NSString *)surname
                                 email:(nonnull NSString *)email
                             cellphone:(nonnull NSString *)cellphone;

@property (nonatomic, readonly, nonnull) NSString * name;

@property (nonatomic, readonly, nonnull) NSString * surname;

@property (nonatomic, readonly, nonnull) NSString * email;

@property (nonatomic, readonly, nonnull) NSString * cellphone;

@end
