// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui_router.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, WALUiRouteAction)
{
    WALUiRouteActionGoTo,
    WALUiRouteActionSetOptionalRoute,
    WALUiRouteActionReplaceWith,
    WALUiRouteActionReplaceAllWith,
};
