// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui_router.djinni

#import "WALRouteInformation.h"
#import <Foundation/Foundation.h>
@class WALUiAlertCallback;


@protocol WALUiNativeRouter

- (void)resetTo:(nonnull WALRouteInformation *)routeInformation;

- (void)goBack;

- (void)showAlert:(nonnull NSString *)title
          message:(nonnull NSString *)message
      button1Text:(nonnull NSString *)button1Text
      button2Text:(nonnull NSString *)button2Text
   buttonCallback:(nullable WALUiAlertCallback *)buttonCallback;

- (void)startLoading:(nonnull NSString *)loadingText;

- (void)stopLoading;

- (void)closeAll;

@end
