// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui_router.djinni

#import "WALRouteInformation.h"
#import <Foundation/Foundation.h>


@interface WALUiRouter : NSObject

- (nonnull WALRouteInformation *)createRouteInformation:(nonnull NSString *)path;

- (void)goTo:(nonnull WALRouteInformation *)routeInformation;

- (void)replaceWith:(nonnull WALRouteInformation *)routeInformation;

- (void)replaceAllWith:(nonnull WALRouteInformation *)routeInformation;

- (void)resetTo:(nonnull WALRouteInformation *)routeInformation;

- (void)goBack;

@end
