// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui_router.djinni

#import "WALUiRouteAction.h"
#import "WALUiRoutePresentationMode.h"
#import <Foundation/Foundation.h>

@interface WALUiRouteInformation : NSObject
- (nonnull instancetype)initWithRouteName:(nonnull NSString *)routeName
                             presentation:(WALUiRoutePresentationMode)presentation
                              routeAction:(WALUiRouteAction)routeAction;
+ (nonnull instancetype)uiRouteInformationWithRouteName:(nonnull NSString *)routeName
                                           presentation:(WALUiRoutePresentationMode)presentation
                                            routeAction:(WALUiRouteAction)routeAction;

@property (nonatomic, readonly, nonnull) NSString * routeName;

@property (nonatomic, readonly) WALUiRoutePresentationMode presentation;

@property (nonatomic, readonly) WALUiRouteAction routeAction;

@end
