// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from web_operation_vm.djinni

#import <Foundation/Foundation.h>

@interface WALWebOperationVm : NSObject
- (nonnull instancetype)initWithExternalUrl:(nonnull NSString *)externalUrl
                                callbackUrl:(nonnull NSString *)callbackUrl;
+ (nonnull instancetype)webOperationVmWithExternalUrl:(nonnull NSString *)externalUrl
                                          callbackUrl:(nonnull NSString *)callbackUrl;

@property (nonatomic, readonly, nonnull) NSString * externalUrl;

@property (nonatomic, readonly, nonnull) NSString * callbackUrl;

@end
